// lib/mock-data.ts

import { CardData } from "@/components/DashboardSectionCard";
import { BudgetCategoryResponse, BudgetResponse } from "@/types/Budget";

const baseDate = new Date("2024-11-01");

const getDateOffset = (daysOffset: number) => {
  const date = new Date(baseDate);
  date.setDate(date.getDate() - daysOffset);
  return date.toISOString();
};

export const getBudgetData = async (): Promise<BudgetResponse[]> => {
  return mockBudgets;
};

export const mockBudgets: BudgetResponse[] = [
  {
    id: "1",
    name: "Grocery Shopping",
    amount: 150.0,
    budgetType: "EXPENSE",
    budgetCategoryName: "Food & Groceries",
    budgetCategoryId: "cat-1",
    createdAt: getDateOffset(29),
  },
  {
    id: "2",
    name: "Monthly Salary",
    amount: 5000.0,
    budgetType: "INCOME",
    budgetCategoryName: "Salary",
    budgetCategoryId: "cat-2",
    createdAt: getDateOffset(28),
  },
  {
    id: "3",
    name: "Electricity Bill",
    amount: 120.5,
    budgetType: "EXPENSE",
    budgetCategoryName: "Utilities",
    budgetCategoryId: "cat-3",
    createdAt: getDateOffset(27),
  },
  {
    id: "4",
    name: "Emergency Fund",
    amount: 500.0,
    budgetType: "SAVINGS",
    budgetCategoryName: "Savings",
    budgetCategoryId: "cat-4",
    createdAt: getDateOffset(26),
  },
  {
    id: "5",
    name: "Stock Investment",
    amount: 1000.0,
    budgetType: "INVESTMENT",
    budgetCategoryName: "Investments",
    budgetCategoryId: "cat-5",
    createdAt: getDateOffset(25),
  },
  {
    id: "6",
    name: "Car Loan Payment",
    amount: 350.0,
    budgetType: "LOAN",
    budgetCategoryName: "Loans",
    budgetCategoryId: "cat-6",
    createdAt: getDateOffset(24),
  },
  {
    id: "7",
    name: "Restaurant Dinner",
    amount: 75.0,
    budgetType: "EXPENSE",
    budgetCategoryName: "Dining",
    budgetCategoryId: "cat-7",
    createdAt: getDateOffset(23),
  },
  {
    id: "8",
    name: "Netflix Subscription",
    amount: 15.99,
    budgetType: "EXPENSE",
    budgetCategoryName: "Entertainment",
    budgetCategoryId: "cat-8",
    createdAt: getDateOffset(22),
  },
  {
    id: "9",
    name: "Gift to Friend",
    amount: 50.0,
    budgetType: "LEND",
    budgetCategoryName: "Lending",
    budgetCategoryId: "cat-9",
    createdAt: getDateOffset(21),
  },
  {
    id: "10",
    name: "Freelance Income",
    amount: 800.0,
    budgetType: "INCOME",
    budgetCategoryName: "Side Income",
    budgetCategoryId: "cat-10",
    createdAt: getDateOffset(20),
  },
  {
    id: "11",
    name: "Gas Station",
    amount: 60.0,
    budgetType: "EXPENSE",
    budgetCategoryName: "Transportation",
    budgetCategoryId: "cat-11",
    createdAt: getDateOffset(19),
  },
  {
    id: "12",
    name: "Bonus Money",
    amount: 200.0,
    budgetType: "EXTRA",
    budgetCategoryName: "Bonus",
    budgetCategoryId: "cat-12",
    createdAt: getDateOffset(18),
  },
  {
    id: "13",
    name: "Water Bill",
    amount: 45.0,
    budgetType: "EXPENSE",
    budgetCategoryName: "Utilities",
    budgetCategoryId: "cat-3",
    createdAt: getDateOffset(17),
  },
  {
    id: "14",
    name: "Gym Membership",
    amount: 50.0,
    budgetType: "EXPENSE",
    budgetCategoryName: "Health & Fitness",
    budgetCategoryId: "cat-13",
    createdAt: getDateOffset(16),
  },
  {
    id: "15",
    name: "Internet Bill",
    amount: 79.99,
    budgetType: "EXPENSE",
    budgetCategoryName: "Utilities",
    budgetCategoryId: "cat-3",
    createdAt: getDateOffset(15),
  },
  {
    id: "16",
    name: "Crypto Investment",
    amount: 500.0,
    budgetType: "INVESTMENT",
    budgetCategoryName: "Investments",
    budgetCategoryId: "cat-5",
    createdAt: getDateOffset(14),
  },
  {
    id: "17",
    name: "Medical Checkup",
    amount: 200.0,
    budgetType: "EXPENSE",
    budgetCategoryName: "Healthcare",
    budgetCategoryId: "cat-14",
    createdAt: getDateOffset(13),
  },
  {
    id: "18",
    name: "Book Purchase",
    amount: 25.0,
    budgetType: "EXPENSE",
    budgetCategoryName: "Education",
    budgetCategoryId: "cat-15",
    createdAt: getDateOffset(12),
  },
  {
    id: "19",
    name: "Coffee & Breakfast",
    amount: 35.0,
    budgetType: "EXPENSE",
    budgetCategoryName: "Dining",
    budgetCategoryId: "cat-7",
    createdAt: getDateOffset(11),
  },
  {
    id: "20",
    name: "Phone Bill",
    amount: 65.0,
    budgetType: "EXPENSE",
    budgetCategoryName: "Utilities",
    budgetCategoryId: "cat-3",
    createdAt: getDateOffset(10),
  },
  {
    id: "21",
    name: "Rent Payment",
    amount: 1200.0,
    budgetType: "EXPENSE",
    budgetCategoryName: "Housing",
    budgetCategoryId: "cat-16",
    createdAt: getDateOffset(9),
  },
  {
    id: "22",
    name: "Clothes Shopping",
    amount: 120.0,
    budgetType: "EXPENSE",
    budgetCategoryName: "Shopping",
    budgetCategoryId: "cat-17",
    createdAt: getDateOffset(8),
  },
  {
    id: "23",
    name: "Vacation Fund",
    amount: 300.0,
    budgetType: "SAVINGS",
    budgetCategoryName: "Savings",
    budgetCategoryId: "cat-4",
    createdAt: getDateOffset(7),
  },
  {
    id: "24",
    name: "Home Loan Interest",
    amount: 800.0,
    budgetType: "LOAN",
    budgetCategoryName: "Loans",
    budgetCategoryId: "cat-6",
    createdAt: getDateOffset(6),
  },
  {
    id: "25",
    name: "Movie Tickets",
    amount: 30.0,
    budgetType: "EXPENSE",
    budgetCategoryName: "Entertainment",
    budgetCategoryId: "cat-8",
    createdAt: getDateOffset(5),
  },
  {
    id: "26",
    name: "Tax Refund",
    amount: 1500.0,
    budgetType: "INCOME",
    budgetCategoryName: "Salary",
    budgetCategoryId: "cat-2",
    createdAt: getDateOffset(4),
  },
  {
    id: "27",
    name: "Furniture Purchase",
    amount: 450.0,
    budgetType: "EXPENSE",
    budgetCategoryName: "Housing",
    budgetCategoryId: "cat-16",
    createdAt: getDateOffset(3),
  },
  {
    id: "28",
    name: "Loan to Brother",
    amount: 200.0,
    budgetType: "LEND",
    budgetCategoryName: "Lending",
    budgetCategoryId: "cat-9",
    createdAt: getDateOffset(2),
  },
  {
    id: "29",
    name: "Spotify Premium",
    amount: 12.99,
    budgetType: "EXPENSE",
    budgetCategoryName: "Entertainment",
    budgetCategoryId: "cat-8",
    createdAt: getDateOffset(1),
  },
  {
    id: "30",
    name: "Year-End Bonus",
    amount: 2000.0,
    budgetType: "EXTRA",
    budgetCategoryName: "Bonus",
    budgetCategoryId: "cat-12",
    createdAt: getDateOffset(0),
  },
];

// Dummy categories
export const dummyCategories: BudgetCategoryResponse[] = [
  {
    id: "cat-1",
    name: "Groceries",
    notes: "Food and household items",
    budgetType: "EXPENSE",
    lastModifiedAt: "2025-10-15T10:30:00",
  },
  {
    id: "cat-2",
    name: "Salary",
    notes: "Monthly income",
    budgetType: "INCOME",
    lastModifiedAt: "2025-10-01T09:00:00",
  },
  {
    id: "cat-3",
    name: "Transportation",
    notes: "Gas, public transport",
    budgetType: "EXPENSE",
    lastModifiedAt: "2025-10-10T14:20:00",
  },
  {
    id: "cat-4",
    name: "Emergency Fund",
    notes: "Rainy day savings",
    budgetType: "SAVINGS",
    lastModifiedAt: "2025-09-20T11:00:00",
  },
  {
    id: "cat-5",
    name: "Stock Portfolio",
    notes: "Investment account",
    budgetType: "INVESTMENT",
    lastModifiedAt: "2025-10-05T16:45:00",
  },
  {
    id: "cat-6",
    name: "Entertainment",
    notes: "Movies, games, hobbies",
    budgetType: "EXTRA",
    lastModifiedAt: "2025-10-12T19:30:00",
  },
];

export const dashboardCards: CardData[] = [
  {
    label: "Total Budget",
    value: "$5,250.00",
    change: 12.5,
    description: "Trending up this month",
    footer: "Budget allocation for this period",
    trend: "up",
  },
  {
    label: "Income",
    value: "$8,500.00",
    change: 8.2,
    description: "Strong income this month",
    footer: "Total earnings received",
    trend: "up",
  },
  {
    label: "Expense",
    value: "$3,250.00",
    change: -5.3,
    description: "Down from last month",
    footer: "Total spending this period",
    trend: "down",
  },
  {
    label: "Recurring Budgets",
    value: "2",
    change: 1,
    description: "New today",
    footer: "Payments auto added today",
    trend: "up",
  },
  {
    label: "Reminders Today",
    value: "3",
    change: 0,
    description: "Pending actions",
    footer: "Payments due today",
    trend: "up",
  },
];
